apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  creationTimestamp: null
  name: argotest2-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "201"
  name: cli-job-sa
  namespace: argotest2-1
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "202"
  name: cli-job-sa-argotest2-1-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: argotest2-1
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "203"
  name: testjob-2-1
  namespace: argotest2-1
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: quay.io/sfhassan/oc_net_tools 
          name: testjob-2-1
          command:
            - /bin/bash
            - -c
            - |
              for count in {1..100}; do echo "job1: " $count; sleep 10; done
