---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "203"
  name: presync2 
  namespace: argotest2
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      # serviceAccount: cli-job-sa
      # serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: quay.io/sfhassan/newtools
          name: presync2
          command:
            - /bin/bash
            - -c
            - |
              while true; do echo ".....presync2...."; sleep 30; done
